set_property PACKAGE_PIN V17 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
set_property PACKAGE_PIN A18 [get_ports o_Tx_Serial]
set_property PACKAGE_PIN B18 [get_ports i_Rx_Serial]
set_property PACKAGE_PIN W5 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports clock]
set_property IOSTANDARD LVCMOS33 [get_ports i_Rx_Serial]
set_property IOSTANDARD LVCMOS33 [get_ports o_Tx_Serial]
set_property SLEW SLOW [get_ports o_Tx_Serial]

set_property PACKAGE_PIN U16 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led1]
set_property IOSTANDARD LVCMOS33 [get_ports led2]
set_property PACKAGE_PIN E19 [get_ports led2]
